version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REPOSITORY: "brain-task-app"

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - echo "Logging in to Amazon ECR"
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY"
      - echo "ECR URI is $ECR_URI"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t "$ECR_REPOSITORY:latest" .
      - docker tag "$ECR_REPOSITORY:latest" "$ECR_URI:latest"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push "$ECR_URI:latest"
      - echo "Docker image pushed successfully"

artifacts:
  files:
    - k8s/deployment.yaml
    - k8s/service.yaml