version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ap-south-1"
    ECR_REPOSITORY: "brain-task-app"
    EKS_CLUSTER_NAME: "brain-task-eks"

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - echo "AWS Region is $AWS_DEFAULT_REGION"
      - echo "ECR Repository is $ECR_REPOSITORY"
      - echo "EKS Cluster is $EKS_CLUSTER_NAME"

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - echo "AWS Account ID is $AWS_ACCOUNT_ID"

      - ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "ECR Registry is $ECR_REGISTRY"

      - echo "Checking ECR repository..."
      - aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_DEFAULT_REGION

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo "ECR login successful"

      - echo "Installing kubectl..."
      - curl -LO https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl
      - install -m 0755 kubectl /usr/local/bin/kubectl
      - kubectl version --client

      - echo "Updating kubeconfig for EKS..."
      - aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name $EKS_CLUSTER_NAME
      - echo "EKS kubeconfig updated"

  build:
    commands:
      - echo "Starting Docker build"
      - docker build -t brain-task-app .
      - echo "Docker image built successfully"

      - echo "Tagging Docker image"
      - docker tag brain-task-app $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo "Docker image tagged successfully"

  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo "Docker image pushed successfully"

      - echo "Deploying application to EKS"
      - kubectl apply -f k8s/deployment.yaml
      - kubectl apply -f k8s/service.yaml

      - echo "Checking Kubernetes deployment"
      - kubectl rollout status deployment/brain-task-deployment --timeout=180s

      - echo "Checking Kubernetes pods"
      - kubectl get pods

      - echo "Checking Kubernetes service"
      - kubectl get svc brain-task-service

      - echo "Deployment completed successfully"